# Site settings
title: Cookie Interactive Inc.
description: The Ultimate Interaction
baseurl: "" # the subpath of your site, e.g., "/blog"
url: "https://seasaintfromsnowingsea.github.io" # the base hostname & URL for your site

# Build settings
markdown: kramdown
theme: null # 중요: 원격 테마를 사용할 때는 기본 테마 설정을 null로 지정합니다.
remote_theme: mmistakes/minimal-mistakes # 원격 테마의 GitHub 경로

# Optional settings
minimal_mistakes_skin: "default" # 테마의 스킨 설정, "air", "aqua", "contrast" 등 다양한 옵션이 있습니다.
locale: "ko-KR" # 사이트의 지역 설정

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
google_site_verification: "your_google_verification_code"
bing_site_verification: "your_bing_verification_code"

# Social Media settings
twitter_username: yourusername
github_username: yourusername
facebook_username: yourusername

# Analytics settings
google_analytics: your_google_analytics_tracking_id
